[install]
# Usar npm como fallback se o Bun não estiver disponível
fallback = "npm"

[install.cache]
# Habilitar cache para builds mais rápidos
dir = ".bun"

[test]
# Configurações para testes
preload = ["./src/test/setup.ts"]

[run]
# Scripts padrão
bunx = "npx"
