// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validação robusta de variáveis de ambiente
console.log('🔍 Verificando variáveis de ambiente Supabase...');
console.log('VITE_SUPABASE_URL:', SUPABASE_URL ? '✅ Configurada' : '❌ Não configurada');
console.log('VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✅ Configurada' : '❌ Não configurada');

if (!SUPABASE_URL) {
  console.error('❌ VITE_SUPABASE_URL não configurada');
  throw new Error('VITE_SUPABASE_URL é obrigatória');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ VITE_SUPABASE_PUBLISHABLE_KEY não configurada');
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY é obrigatória');
}

// Validar formato das variáveis
if (!SUPABASE_URL.startsWith('https://')) {
  throw new Error('VITE_SUPABASE_URL deve começar com https://');
}

if (!SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')) {
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY deve ser um JWT válido');
}

const url = SUPABASE_URL;
const key = SUPABASE_PUBLISHABLE_KEY;

console.log('✅ Variáveis de ambiente validadas com sucesso');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    // Configurações para lidar com third-party cookies bloqueados
    storageKey: 'supabase.auth.token',
    flowType: 'pkce',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  global: {
    headers: {
      'X-Client-Info': 'comps-plus-54',
    },
  },
});

// Teste de conexão em todos os ambientes
console.log('🔗 Testando conexão com Supabase...');
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    console.error('❌ Erro na conexão Supabase:', error.message);
    console.error('❌ Detalhes do erro:', error);
  } else {
    console.log('✅ Conexão com Supabase estabelecida');
    console.log('📊 Sessão:', data.session ? 'Ativa' : 'Não ativa');
  }
}).catch((error) => {
  console.error('❌ Erro crítico na conexão Supabase:', error);
});